[2025-02-28T14:24:03.795+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-28T14:24:03.828+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transformed_s3_to_redshift.copy_data_from_s3 scheduled__2025-02-27T00:00:00+00:00 [queued]>
[2025-02-28T14:24:03.842+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transformed_s3_to_redshift.copy_data_from_s3 scheduled__2025-02-27T00:00:00+00:00 [queued]>
[2025-02-28T14:24:03.844+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-28T14:24:03.862+0000] {taskinstance.py:2890} INFO - Executing <Task(RedshiftDataOperator): copy_data_from_s3> on 2025-02-27 00:00:00+00:00
[2025-02-28T14:24:03.881+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2439) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-28T14:24:03.883+0000] {standard_task_runner.py:72} INFO - Started process 2441 to run task
[2025-02-28T14:24:03.882+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'transformed_s3_to_redshift', 'copy_data_from_s3', 'scheduled__2025-02-27T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/transformed_data_dag.py', '--cfg-path', '/tmp/tmpt7rhkfwx']
[2025-02-28T14:24:03.885+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask copy_data_from_s3
[2025-02-28T14:24:03.906+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-28T14:24:03.961+0000] {task_command.py:467} INFO - Running <TaskInstance: transformed_s3_to_redshift.copy_data_from_s3 scheduled__2025-02-27T00:00:00+00:00 [running]> on host 12d1914ba335
[2025-02-28T14:24:03.963+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-28T14:24:04.090+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transformed_s3_to_redshift' AIRFLOW_CTX_TASK_ID='copy_data_from_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-27T00:00:00+00:00'
[2025-02-28T14:24:04.093+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-28T14:24:04.152+0000] {redshift_data.py:135} INFO - Executing statement: 
COPY my_table
FROM 's3://dataingestionjson/redshift_data/'
IAM_ROLE 'arn:aws:iam::205930619042:role/aws-service-role/redshift.amazonaws.com/AWSServiceRoleForRedshift'
FORMAT AS PARQUET;
[2025-02-28T14:24:04.170+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-28T14:24:04.171+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-02-28T14:24:05.707+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/redshift_data.py", line 142, in execute
    query_execution_output = self.hook.execute_query(
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 153, in execute_query
    resp = self.conn.execute_statement(**trim_none_values(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the ExecuteStatement operation: User: arn:aws:iam::205930619042:user/andlalit is not authorized to perform: redshift-data:ExecuteStatement on resource: arn:aws:redshift:us-east-1:205930619042:cluster:redshift-cluster-1 because no identity-based policy allows the redshift-data:ExecuteStatement action
[2025-02-28T14:24:05.731+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=transformed_s3_to_redshift, task_id=copy_data_from_s3, run_id=scheduled__2025-02-27T00:00:00+00:00, execution_date=20250227T000000, start_date=20250228T142403, end_date=20250228T142405
[2025-02-28T14:24:05.782+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-28T14:24:05.783+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 72 for task copy_data_from_s3 (An error occurred (AccessDeniedException) when calling the ExecuteStatement operation: User: arn:aws:iam::205930619042:user/andlalit is not authorized to perform: redshift-data:ExecuteStatement on resource: arn:aws:redshift:us-east-1:205930619042:cluster:redshift-cluster-1 because no identity-based policy allows the redshift-data:ExecuteStatement action; 2441)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/redshift_data.py", line 142, in execute
    query_execution_output = self.hook.execute_query(
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 153, in execute_query
    resp = self.conn.execute_statement(**trim_none_values(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the ExecuteStatement operation: User: arn:aws:iam::205930619042:user/andlalit is not authorized to perform: redshift-data:ExecuteStatement on resource: arn:aws:redshift:us-east-1:205930619042:cluster:redshift-cluster-1 because no identity-based policy allows the redshift-data:ExecuteStatement action
[2025-02-28T14:24:05.809+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-28T14:24:05.834+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-28T14:24:05.838+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
