[2025-03-01T03:38:07.135+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-01T03:38:07.157+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_redshift_using_glue.create_redshift_schema scheduled__2025-02-28T00:00:00+00:00 [queued]>
[2025-03-01T03:38:07.166+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_redshift_using_glue.create_redshift_schema scheduled__2025-02-28T00:00:00+00:00 [queued]>
[2025-03-01T03:38:07.167+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-01T03:38:07.180+0000] {taskinstance.py:2890} INFO - Executing <Task(RedshiftDataOperator): create_redshift_schema> on 2025-02-28 00:00:00+00:00
[2025-03-01T03:38:07.186+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=340) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-01T03:38:07.188+0000] {standard_task_runner.py:72} INFO - Started process 341 to run task
[2025-03-01T03:38:07.187+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 's3_to_redshift_using_glue', 'create_redshift_schema', 'scheduled__2025-02-28T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/transformed_data_dag.py', '--cfg-path', '/tmp/tmpgamtitp9']
[2025-03-01T03:38:07.189+0000] {standard_task_runner.py:105} INFO - Job 90: Subtask create_redshift_schema
[2025-03-01T03:38:07.204+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-01T03:38:07.245+0000] {task_command.py:467} INFO - Running <TaskInstance: s3_to_redshift_using_glue.create_redshift_schema scheduled__2025-02-28T00:00:00+00:00 [running]> on host ba37d1932f36
[2025-03-01T03:38:07.247+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-01T03:38:07.342+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_redshift_using_glue' AIRFLOW_CTX_TASK_ID='create_redshift_schema' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-28T00:00:00+00:00'
[2025-03-01T03:38:07.343+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-01T03:38:07.362+0000] {redshift_data.py:135} INFO - Executing statement: 
CREATE EXTERNAL SCHEMA IF NOT EXISTS spectrum_schema
FROM DATA CATALOG DATABASE 'transformed_db'
IAM_ROLE 'arn:aws:iam::205930619042:role/redshift_cluster_lalit';
[2025-03-01T03:38:07.372+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-03-01T03:38:07.373+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-03-01T03:38:08.795+0000] {redshift_data.py:164} INFO - Polling statement 164741b1-8848-453c-bf50-5dfd61bf6c15
[2025-03-01T03:38:09.079+0000] {redshift_data.py:193} INFO - Query status: STARTED
[2025-03-01T03:38:19.081+0000] {redshift_data.py:164} INFO - Polling statement 164741b1-8848-453c-bf50-5dfd61bf6c15
[2025-03-01T03:38:19.385+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/redshift_data.py", line 142, in execute
    query_execution_output = self.hook.execute_query(
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 158, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 165, in wait_for_results
    is_finished = self.check_query_is_finished(statement_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 174, in check_query_is_finished
    return self.parse_statement_response(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 188, in parse_statement_response
    raise exception_cls(
airflow.providers.amazon.aws.hooks.redshift_data.RedshiftDataQueryFailedError: Statement 164741b1-8848-453c-bf50-5dfd61bf6c15 terminated with status FAILED. Response details: {'ClusterIdentifier': 'redshift-cluster-1',
 'CreatedAt': datetime.datetime(2025, 3, 1, 3, 38, 8, 173000, tzinfo=tzlocal()),
 'Database': 'dev',
 'DbUser': 'IAM:andlalit',
 'Duration': -1,
 'Error': 'ERROR: permission denied for database dev',
 'HasResultSet': False,
 'Id': '164741b1-8848-453c-bf50-5dfd61bf6c15',
 'QueryString': '\n'
                'CREATE EXTERNAL SCHEMA IF NOT EXISTS spectrum_schema\n'
                "FROM DATA CATALOG DATABASE 'transformed_db'\n"
                "IAM_ROLE '';",
 'RedshiftPid': 1073946990,
 'RedshiftQueryId': -1,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '520',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 01 Mar 2025 03:38:18 GMT',
                                      'x-amzn-requestid': 'e6e5a877-40bb-4869-a8cd-c2a37982e23e'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'e6e5a877-40bb-4869-a8cd-c2a37982e23e',
                      'RetryAttempts': 0},
 'ResultFormat': 'json',
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 3, 1, 3, 38, 8, 706000, tzinfo=tzlocal())}
[2025-03-01T03:38:19.395+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=s3_to_redshift_using_glue, task_id=create_redshift_schema, run_id=scheduled__2025-02-28T00:00:00+00:00, execution_date=20250228T000000, start_date=20250301T033807, end_date=20250301T033819
[2025-03-01T03:38:19.425+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-01T03:38:19.426+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 90 for task create_redshift_schema (Statement 164741b1-8848-453c-bf50-5dfd61bf6c15 terminated with status FAILED. Response details: {'ClusterIdentifier': 'redshift-cluster-1',
 'CreatedAt': datetime.datetime(2025, 3, 1, 3, 38, 8, 173000, tzinfo=tzlocal()),
 'Database': 'dev',
 'DbUser': 'IAM:andlalit',
 'Duration': -1,
 'Error': 'ERROR: permission denied for database dev',
 'HasResultSet': False,
 'Id': '164741b1-8848-453c-bf50-5dfd61bf6c15',
 'QueryString': '\n'
                'CREATE EXTERNAL SCHEMA IF NOT EXISTS spectrum_schema\n'
                "FROM DATA CATALOG DATABASE 'transformed_db'\n"
                "IAM_ROLE '';",
 'RedshiftPid': 1073946990,
 'RedshiftQueryId': -1,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '520',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 01 Mar 2025 03:38:18 GMT',
                                      'x-amzn-requestid': 'e6e5a877-40bb-4869-a8cd-c2a37982e23e'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'e6e5a877-40bb-4869-a8cd-c2a37982e23e',
                      'RetryAttempts': 0},
 'ResultFormat': 'json',
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 3, 1, 3, 38, 8, 706000, tzinfo=tzlocal())}; 341)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/redshift_data.py", line 142, in execute
    query_execution_output = self.hook.execute_query(
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 158, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 165, in wait_for_results
    is_finished = self.check_query_is_finished(statement_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 174, in check_query_is_finished
    return self.parse_statement_response(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 188, in parse_statement_response
    raise exception_cls(
airflow.providers.amazon.aws.hooks.redshift_data.RedshiftDataQueryFailedError: Statement 164741b1-8848-453c-bf50-5dfd61bf6c15 terminated with status FAILED. Response details: {'ClusterIdentifier': 'redshift-cluster-1',
 'CreatedAt': datetime.datetime(2025, 3, 1, 3, 38, 8, 173000, tzinfo=tzlocal()),
 'Database': 'dev',
 'DbUser': 'IAM:andlalit',
 'Duration': -1,
 'Error': 'ERROR: permission denied for database dev',
 'HasResultSet': False,
 'Id': '164741b1-8848-453c-bf50-5dfd61bf6c15',
 'QueryString': '\n'
                'CREATE EXTERNAL SCHEMA IF NOT EXISTS spectrum_schema\n'
                "FROM DATA CATALOG DATABASE 'transformed_db'\n"
                "IAM_ROLE '';",
 'RedshiftPid': 1073946990,
 'RedshiftQueryId': -1,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '520',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 01 Mar 2025 03:38:18 GMT',
                                      'x-amzn-requestid': 'e6e5a877-40bb-4869-a8cd-c2a37982e23e'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'e6e5a877-40bb-4869-a8cd-c2a37982e23e',
                      'RetryAttempts': 0},
 'ResultFormat': 'json',
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 3, 1, 3, 38, 8, 706000, tzinfo=tzlocal())}
[2025-03-01T03:38:19.457+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-01T03:38:19.483+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-01T03:38:19.486+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
