[2025-02-28T15:42:13.226+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-28T15:42:13.254+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_redshift_using_glue.run_glue_crawler scheduled__2025-02-27T00:00:00+00:00 [queued]>
[2025-02-28T15:42:13.267+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_redshift_using_glue.run_glue_crawler scheduled__2025-02-27T00:00:00+00:00 [queued]>
[2025-02-28T15:42:13.268+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-28T15:42:13.289+0000] {taskinstance.py:2890} INFO - Executing <Task(GlueCrawlerOperator): run_glue_crawler> on 2025-02-27 00:00:00+00:00
[2025-02-28T15:42:13.302+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=812) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-28T15:42:13.303+0000] {standard_task_runner.py:72} INFO - Started process 814 to run task
[2025-02-28T15:42:13.302+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 's3_to_redshift_using_glue', 'run_glue_crawler', 'scheduled__2025-02-27T00:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/transformed_data_dag.py', '--cfg-path', '/tmp/tmpd4pdtyk2']
[2025-02-28T15:42:13.305+0000] {standard_task_runner.py:105} INFO - Job 75: Subtask run_glue_crawler
[2025-02-28T15:42:13.326+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-28T15:42:13.383+0000] {task_command.py:467} INFO - Running <TaskInstance: s3_to_redshift_using_glue.run_glue_crawler scheduled__2025-02-27T00:00:00+00:00 [running]> on host ba37d1932f36
[2025-02-28T15:42:13.385+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-28T15:42:13.521+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_redshift_using_glue' AIRFLOW_CTX_TASK_ID='run_glue_crawler' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-27T00:00:00+00:00'
[2025-02-28T15:42:13.522+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-28T15:42:13.585+0000] {glue_crawler.py:57} INFO - Checking if crawler already exists: redshift_parquet_crawler
[2025-02-28T15:42:13.599+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-28T15:42:13.600+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-02-28T15:42:14.934+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/glue_crawler.py", line 94, in execute
    if self.hook.has_crawler(crawler_name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue_crawler.py", line 60, in has_crawler
    self.get_crawler(crawler_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue_crawler.py", line 75, in get_crawler
    return self.glue_client.get_crawler(Name=crawler_name)["Crawler"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the GetCrawler operation: User: arn:aws:iam::205930619042:user/andlalit is not authorized to perform: glue:GetCrawler on resource: arn:aws:glue:us-east-1:205930619042:crawler/redshift_parquet_crawler because no identity-based policy allows the glue:GetCrawler action
[2025-02-28T15:42:14.947+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=s3_to_redshift_using_glue, task_id=run_glue_crawler, run_id=scheduled__2025-02-27T00:00:00+00:00, execution_date=20250227T000000, start_date=20250228T154213, end_date=20250228T154214
[2025-02-28T15:42:14.987+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-28T15:42:14.987+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 75 for task run_glue_crawler (An error occurred (AccessDeniedException) when calling the GetCrawler operation: User: arn:aws:iam::205930619042:user/andlalit is not authorized to perform: glue:GetCrawler on resource: arn:aws:glue:us-east-1:205930619042:crawler/redshift_parquet_crawler because no identity-based policy allows the glue:GetCrawler action; 814)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/glue_crawler.py", line 94, in execute
    if self.hook.has_crawler(crawler_name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue_crawler.py", line 60, in has_crawler
    self.get_crawler(crawler_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue_crawler.py", line 75, in get_crawler
    return self.glue_client.get_crawler(Name=crawler_name)["Crawler"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the GetCrawler operation: User: arn:aws:iam::205930619042:user/andlalit is not authorized to perform: glue:GetCrawler on resource: arn:aws:glue:us-east-1:205930619042:crawler/redshift_parquet_crawler because no identity-based policy allows the glue:GetCrawler action
[2025-02-28T15:42:15.005+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-28T15:42:15.037+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-28T15:42:15.041+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
