[2025-02-27T06:01:37.178+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-27T06:01:37.203+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: glue_transformation.transformation manual__2025-02-27T05:51:32.016295+00:00 [queued]>
[2025-02-27T06:01:37.217+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: glue_transformation.transformation manual__2025-02-27T05:51:32.016295+00:00 [queued]>
[2025-02-27T06:01:37.218+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-02-27T06:01:37.234+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): transformation> on 2025-02-27 05:51:32.016295+00:00
[2025-02-27T06:01:37.242+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=987) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-27T06:01:37.244+0000] {standard_task_runner.py:72} INFO - Started process 988 to run task
[2025-02-27T06:01:37.242+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'glue_transformation', 'transformation', 'manual__2025-02-27T05:51:32.016295+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/transformation_dag.py', '--cfg-path', '/tmp/tmpyr3nshlu']
[2025-02-27T06:01:37.245+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask transformation
[2025-02-27T06:01:37.263+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-27T06:01:37.307+0000] {task_command.py:467} INFO - Running <TaskInstance: glue_transformation.transformation manual__2025-02-27T05:51:32.016295+00:00 [running]> on host 5251e7c2bcd3
[2025-02-27T06:01:37.402+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='glue_transformation' AIRFLOW_CTX_TASK_ID='transformation' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T05:51:32.016295+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-27T05:51:32.016295+00:00'
[2025-02-27T06:01:37.403+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-27T06:01:37.425+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-27T06:01:37.426+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/transformation.py']
[2025-02-27T06:01:37.436+0000] {subprocess.py:99} INFO - Output:
[2025-02-27T06:01:38.121+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-02-27T06:01:38.122+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/scripts/transformation.py", line 3, in <module>
[2025-02-27T06:01:38.122+0000] {subprocess.py:106} INFO -     from awsglue.context import GlueContext
[2025-02-27T06:01:38.123+0000] {subprocess.py:106} INFO - ModuleNotFoundError: No module named 'awsglue'
[2025-02-27T06:01:38.163+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-27T06:01:38.177+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-27T06:01:38.182+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=glue_transformation, task_id=transformation, run_id=manual__2025-02-27T05:51:32.016295+00:00, execution_date=20250227T055132, start_date=20250227T060137, end_date=20250227T060138
[2025-02-27T06:01:38.215+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-27T06:01:38.216+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task transformation (Bash command failed. The command returned a non-zero exit code 1.; 988)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-27T06:01:38.248+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-27T06:01:38.267+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-27T06:01:38.269+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
