[2025-02-28T14:26:49.358+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-28T14:26:49.386+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transformed_s3_to_redshift.copy_data_from_s3 manual__2025-02-28T14:26:47.847989+00:00 [queued]>
[2025-02-28T14:26:49.402+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transformed_s3_to_redshift.copy_data_from_s3 manual__2025-02-28T14:26:47.847989+00:00 [queued]>
[2025-02-28T14:26:49.403+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-28T14:26:49.427+0000] {taskinstance.py:2890} INFO - Executing <Task(RedshiftDataOperator): copy_data_from_s3> on 2025-02-28 14:26:47.847989+00:00
[2025-02-28T14:26:49.438+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2569) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-28T14:26:49.440+0000] {standard_task_runner.py:72} INFO - Started process 2570 to run task
[2025-02-28T14:26:49.438+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'transformed_s3_to_redshift', 'copy_data_from_s3', 'manual__2025-02-28T14:26:47.847989+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/transformed_data_dag.py', '--cfg-path', '/tmp/tmpwu57_tb0']
[2025-02-28T14:26:49.442+0000] {standard_task_runner.py:105} INFO - Job 73: Subtask copy_data_from_s3
[2025-02-28T14:26:49.462+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-28T14:26:49.507+0000] {task_command.py:467} INFO - Running <TaskInstance: transformed_s3_to_redshift.copy_data_from_s3 manual__2025-02-28T14:26:47.847989+00:00 [running]> on host 12d1914ba335
[2025-02-28T14:26:49.599+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transformed_s3_to_redshift' AIRFLOW_CTX_TASK_ID='copy_data_from_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T14:26:47.847989+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-28T14:26:47.847989+00:00'
[2025-02-28T14:26:49.600+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-28T14:26:49.618+0000] {redshift_data.py:135} INFO - Executing statement: 
COPY my_table
FROM 's3://dataingestionjson/redshift_data/'
IAM_ROLE 'arn:aws:iam::205930619042:role/aws-service-role/redshift.amazonaws.com/AWSServiceRoleForRedshift'
FORMAT AS PARQUET;
[2025-02-28T14:26:49.630+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-28T14:26:49.631+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-02-28T14:26:51.125+0000] {redshift_data.py:164} INFO - Polling statement f76bc8bc-c1f5-435b-8506-beadddf1c6da
[2025-02-28T14:26:51.378+0000] {redshift_data.py:193} INFO - Query status: PICKED
[2025-02-28T14:27:01.380+0000] {redshift_data.py:164} INFO - Polling statement f76bc8bc-c1f5-435b-8506-beadddf1c6da
[2025-02-28T14:27:01.700+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/redshift_data.py", line 142, in execute
    query_execution_output = self.hook.execute_query(
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 158, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 165, in wait_for_results
    is_finished = self.check_query_is_finished(statement_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 174, in check_query_is_finished
    return self.parse_statement_response(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 188, in parse_statement_response
    raise exception_cls(
airflow.providers.amazon.aws.hooks.redshift_data.RedshiftDataQueryFailedError: Statement f76bc8bc-c1f5-435b-8506-beadddf1c6da terminated with status FAILED. Response details: {'ClusterIdentifier': 'redshift-cluster-1',
 'CreatedAt': datetime.datetime(2025, 2, 28, 14, 26, 51, 192000, tzinfo=tzlocal()),
 'Database': 'dev',
 'DbUser': 'IAM:andlalit',
 'Duration': -1,
 'Error': 'ERROR: Cannot COPY into nonexistent table my_table',
 'HasResultSet': False,
 'Id': 'f76bc8bc-c1f5-435b-8506-beadddf1c6da',
 'QueryString': '\n'
                'COPY my_table\n'
                "FROM 's3://dataingestionjson/redshift_data/'\n"
                "IAM_ROLE ''\n"
                'FORMAT AS PARQUET;',
 'RedshiftPid': 1073889708,
 'RedshiftQueryId': -1,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '510',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Fri, 28 Feb 2025 14:27:01 GMT',
                                      'x-amzn-requestid': 'fa0f4ec3-c835-46f5-bcdf-0679d08a6d53'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'fa0f4ec3-c835-46f5-bcdf-0679d08a6d53',
                      'RetryAttempts': 0},
 'ResultFormat': 'json',
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 2, 28, 14, 26, 51, 808000, tzinfo=tzlocal())}
[2025-02-28T14:27:01.713+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=transformed_s3_to_redshift, task_id=copy_data_from_s3, run_id=manual__2025-02-28T14:26:47.847989+00:00, execution_date=20250228T142647, start_date=20250228T142649, end_date=20250228T142701
[2025-02-28T14:27:01.745+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-28T14:27:01.746+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 73 for task copy_data_from_s3 (Statement f76bc8bc-c1f5-435b-8506-beadddf1c6da terminated with status FAILED. Response details: {'ClusterIdentifier': 'redshift-cluster-1',
 'CreatedAt': datetime.datetime(2025, 2, 28, 14, 26, 51, 192000, tzinfo=tzlocal()),
 'Database': 'dev',
 'DbUser': 'IAM:andlalit',
 'Duration': -1,
 'Error': 'ERROR: Cannot COPY into nonexistent table my_table',
 'HasResultSet': False,
 'Id': 'f76bc8bc-c1f5-435b-8506-beadddf1c6da',
 'QueryString': '\n'
                'COPY my_table\n'
                "FROM 's3://dataingestionjson/redshift_data/'\n"
                "IAM_ROLE ''\n"
                'FORMAT AS PARQUET;',
 'RedshiftPid': 1073889708,
 'RedshiftQueryId': -1,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '510',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Fri, 28 Feb 2025 14:27:01 GMT',
                                      'x-amzn-requestid': 'fa0f4ec3-c835-46f5-bcdf-0679d08a6d53'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'fa0f4ec3-c835-46f5-bcdf-0679d08a6d53',
                      'RetryAttempts': 0},
 'ResultFormat': 'json',
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 2, 28, 14, 26, 51, 808000, tzinfo=tzlocal())}; 2570)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/redshift_data.py", line 142, in execute
    query_execution_output = self.hook.execute_query(
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 158, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 165, in wait_for_results
    is_finished = self.check_query_is_finished(statement_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 174, in check_query_is_finished
    return self.parse_statement_response(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 188, in parse_statement_response
    raise exception_cls(
airflow.providers.amazon.aws.hooks.redshift_data.RedshiftDataQueryFailedError: Statement f76bc8bc-c1f5-435b-8506-beadddf1c6da terminated with status FAILED. Response details: {'ClusterIdentifier': 'redshift-cluster-1',
 'CreatedAt': datetime.datetime(2025, 2, 28, 14, 26, 51, 192000, tzinfo=tzlocal()),
 'Database': 'dev',
 'DbUser': 'IAM:andlalit',
 'Duration': -1,
 'Error': 'ERROR: Cannot COPY into nonexistent table my_table',
 'HasResultSet': False,
 'Id': 'f76bc8bc-c1f5-435b-8506-beadddf1c6da',
 'QueryString': '\n'
                'COPY my_table\n'
                "FROM 's3://dataingestionjson/redshift_data/'\n"
                "IAM_ROLE ''\n"
                'FORMAT AS PARQUET;',
 'RedshiftPid': 1073889708,
 'RedshiftQueryId': -1,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '510',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Fri, 28 Feb 2025 14:27:01 GMT',
                                      'x-amzn-requestid': 'fa0f4ec3-c835-46f5-bcdf-0679d08a6d53'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'fa0f4ec3-c835-46f5-bcdf-0679d08a6d53',
                      'RetryAttempts': 0},
 'ResultFormat': 'json',
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 2, 28, 14, 26, 51, 808000, tzinfo=tzlocal())}
[2025-02-28T14:27:01.776+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-28T14:27:01.794+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-28T14:27:01.796+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
